name: Build docker images and push to Docker Hub

on:
  push:
    branches:
      - "main"
    paths:
      - "containers/**"

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          ./containers/generate_dockerfile.sh base
      - name: Build and push coder-base
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          file: containers/Dockerfile.base.full
          push: true
          tags: zelinf/coder-base:latest
  ghcup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          ./containers/generate_dockerfile.sh ghcup
      - name: Build and push coder-ghcup
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          file: containers/Dockerfile.ghcup.full
          push: true
          tags: zelinf/coder-ghcup:latest
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          ./containers/generate_dockerfile.sh nix
      - name: Build and push coder-nix
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          file: containers/Dockerfile.nix.full
          push: true
          tags: zelinf/coder-nix:latest
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          ./containers/generate_dockerfile.sh rust
      - name: Build and push coder-rust
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          file: containers/Dockerfile.rust.full
          push: true
          tags: zelinf/coder-rust:latest
