name: Build docker images and push to Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: ./generate_dockerfile.sh nix
      - name: Build and push coder-nix
        uses: docker/build-push-action@v5
        with:
          context: ./containers
          file: containers/Dockerfile.nix.full
          push: true
          tags: zelinf/coder-nix:latest
